# Generated by Django 5.0 on 2026-01-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_inicio', models.DateField(auto_now_add=True)),
                ('especialidad', models.CharField(choices=[('Corazon', 'Cardiologo'), ('Cerebro', 'Neurologo'), ('Huesos', 'Traumatologo')], max_length=50)),
            ],
        ),
    ]
